config/routes.rb
ProjectNew::Application.routes.draw do
  get "welcome/index"
  resources :pictures
  resources :articles
  resources :posts

  get "welcome/index"
  get "welcome/new"

  root 'welcome#index'

  

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :teachers
  has_many :subjects, through: :teachers
end

app/models/chair.rb
class Chair < ActiveRecord::Base
end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/employe.rb
class Employe < ActiveRecord::Base
  has_many :projects
  has_many :managers, through: :projects
  has_many :pictures, as: :imageable
  has_many :subordinates, class_name: "Employe",
           foreign_key: "manager_id"

  belongs_to :manager, class_name: "Employe"
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/krish.rb
class Krish < ActiveRecord::Base

  validates :name, presence: true, length: { minimum: 3 }
  validates :is_success, acceptance: {accept:true}
  # validates :email, confirmation: true
  validates :name, exclusion: { in: %w(www us ca jp),
                                     message: "%{value} is reserved." }
  validates :location, format: { with: /\A[a-zA-Z]+\z/,
                                    message: "only allows letters" }

  validates :name, uniqueness: { scope: :location,
                                 message: "should happen once per year" }



  end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_many :projects
  has_many :employes, through: :projects
end

app/models/mobile.rb
class Mobile < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base

belongs_to :customer
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/pencil.rb
class Pencil < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  validates :name, presence: true
  validates :is_success, acceptance: { accept: 'yes'}
  validates :imageable_type, exclusion: { in: %w(www us ca jp),
                                     message: "%{value} is reserved." }
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :pictures, as: :imageable
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :employe
  belongs_to :manager
end

app/models/raj.rb
class Raj < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :teachers
  has_many :book, through :teachers


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    render :layout => "picture"
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :imageable_id, :imageable_type)
    end
  private

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :imageable_id %><br>
    <%= f.number_field :imageable_id %>
  </div>
  <div class="field">
    <%= f.label :imageable_type %><br>
    <%= f.text_field :imageable_type %>
  </div>
    <div class="field">
      <%= f.label :is_success %><br>
      <%= f.check_box :is_success %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Imageable</th>
      <th>Imageable type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.imageable_id %></td>
        <td><%= picture.imageable_type %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Imageable:</strong>
  <%= @picture.imageable_id %>
</p>

<p>
  <strong>Imageable type:</strong>
  <%= @picture.imageable_type %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>